import { SkillNode } from "../../types/pet";

export const SKILL_NODES: SkillNode[] = [
  // --- TRICKS & AGILITY ---
  {
    id: "fetch_master",
    name: "Fetch Master",
    icon: "🎾",
    category: "tricks",
    tier: 1,
    cost: 20,
    description: "Train your dog in the art of the perfect fetch sprint.",
    benefit: "Unlocks & enhances tennis ball fetch with 1.5x score, gold flair, and faster sprint!",
    prerequisites: [],
    actionUnlocked: "fetch",
  },
  {
    id: "roll_over",
    name: "Belly Rub Roll",
    icon: "🔄",
    category: "tricks",
    tier: 1,
    cost: 25,
    description: "Teaches your pup to playfully flop over on their back.",
    benefit: "Unlocks the roll-over trick! Flopping on grass restores +10 Joy and begs for belly rubs.",
    prerequisites: [],
    actionUnlocked: "roll",
  },
  {
    id: "tornado_spin",
    name: "Tornado Spin",
    icon: "💫",
    category: "tricks",
    tier: 2,
    cost: 45,
    description: "An excited high-speed tail-chasing spin that dazzles everyone at the park.",
    benefit: "Unlocks the spin trick! Entertains onlookers and boosts agility.",
    prerequisites: ["roll_over"],
    actionUnlocked: "spin",
  },
  {
    id: "tap_dance",
    name: "Canine Tap Dance",
    icon: "🕺",
    category: "tricks",
    tier: 2,
    cost: 55,
    description: "Teach your pup to stand upright on hind legs and tap-dance with front paws.",
    benefit: "Unlocks the happy dance trick! Generates +15 Joy and cheerful rhythm.",
    prerequisites: ["roll_over"],
    actionUnlocked: "dance",
  },
  {
    id: "aerial_backflip",
    name: "Acrobatic Backflip",
    icon: "🤸",
    category: "tricks",
    tier: 3,
    cost: 80,
    description: "The crown jewel of canine acrobatics: a full 360-degree aerial flip!",
    benefit: "Unlocks the spectacular backflip! Spectacular crowd cheer, +20 Joy, and +25 XP.",
    prerequisites: ["tap_dance", "tornado_spin"],
    actionUnlocked: "backflip",
  },

  // --- BOND & AFFECTION ---
  {
    id: "handshake_paw",
    name: "Polite Handshake",
    icon: "🐾",
    category: "affection",
    tier: 1,
    cost: 20,
    description: "A gentle greeting where your pup politely offers a high-held front paw.",
    benefit: "Unlocks the give-paw handshake trick! Deepens owner bonding.",
    prerequisites: [],
    actionUnlocked: "handshake",
  },
  {
    id: "cozy_cuddle",
    name: "Cozy Cuddle",
    icon: "🧸",
    category: "affection",
    tier: 2,
    cost: 40,
    description: "Snuggle close together in the warm sun for emotional reassurance.",
    benefit: "Unlocks the cuddle behavior! Provides an instant +25 Joy boost and heart particle aura.",
    prerequisites: ["handshake_paw"],
    actionUnlocked: "cuddle",
  },
  {
    id: "musical_howl",
    name: "Heartfelt Awoo",
    icon: "🎶",
    category: "affection",
    tier: 2,
    cost: 50,
    description: "Lifts snout to the sky to sing a melodious, joyful canine howl.",
    benefit: "Unlocks the happy howl trick! Expresses deep canine soulfulness and joy.",
    prerequisites: ["handshake_paw"],
    actionUnlocked: "howl",
  },
  {
    id: "pure_heart",
    name: "Loving Heart",
    icon: "💖",
    category: "affection",
    tier: 3,
    cost: 75,
    description: "A permanent psychological bond of unconditional devotion.",
    benefit: "Passive Perk: Petting your dog grants double Joy (+16 Joy) and bonus XP every time!",
    prerequisites: ["cozy_cuddle", "musical_howl"],
    isPassive: true,
    passiveEffect: "double_pet_joy",
  },

  // --- VITALITY & INSTINCTS ---
  {
    id: "park_zoomies",
    name: "Park Zoomies",
    icon: "⚡",
    category: "vitality",
    tier: 1,
    cost: 30,
    description: "Unleash sudden bursts of chaotic joy running in rapid loops across the grass.",
    benefit: "Unlocks the zoomies sprint! Recharges pet spirit and blows off steam.",
    prerequisites: [],
    actionUnlocked: "zoomies",
  },
  {
    id: "iron_stomach",
    name: "Gourmet Digestion",
    icon: "🍖",
    category: "vitality",
    tier: 2,
    cost: 50,
    description: "Optimized nutrition efficiency from years of healthy park living.",
    benefit: "Passive Perk: All treats fed from the pantry grant +25% extra Energy boost!",
    prerequisites: ["park_zoomies"],
    isPassive: true,
    passiveEffect: "treat_bonus_energy",
  },
  {
    id: "treasure_hunter",
    name: "Sniff & Scavenge",
    icon: "🪙",
    category: "vitality",
    tier: 2,
    cost: 60,
    description: "A keen canine nose attuned to spotting hidden coins and rewards.",
    benefit: "Passive Perk: Mini-games and fetch games award +50% bonus coins!",
    prerequisites: ["park_zoomies"],
    isPassive: true,
    passiveEffect: "bonus_coins",
  },
  {
    id: "deep_zen_nap",
    name: "Deep Zen Rest",
    icon: "💤",
    category: "vitality",
    tier: 3,
    cost: 75,
    description: "Mastery of restorative sleep and tranquil mindfulness.",
    benefit: "Passive Perk: Resting restores +40% Energy (instead of standard +25%) in peaceful slumber!",
    prerequisites: ["iron_stomach", "treasure_hunter"],
    isPassive: true,
    passiveEffect: "fast_energy_recovery",
  },
];
