import { TreatItem } from "../../types/pet";

export const AVAILABLE_TREATS: TreatItem[] = [
  {
    id: "biscuit",
    name: "Crunchy Golden Bone",
    icon: "🦴",
    energyBoost: 18,
    happinessBoost: 12,
    hungerReduction: 20,
    cost: 10,
    description: "Classic oven-baked bone biscuit that gives quick energy and healthy teeth.",
  },
  {
    id: "beef_jerky",
    name: "Tender Prime Beef Jerky",
    icon: "🍖",
    energyBoost: 28,
    happinessBoost: 22,
    hungerReduction: 35,
    cost: 25,
    description: "Rich protein-packed savory beef strips every dog goes wild for.",
  },
  {
    id: "cheddar",
    name: "Gourmet Aged Cheddar Bite",
    icon: "🧀",
    energyBoost: 38,
    happinessBoost: 30,
    hungerReduction: 40,
    cost: 40,
    description: "Creamy gourmet cheese chunk for high-speed park zoomies!",
  },
  {
    id: "carrot",
    name: "Sweet Garden Carrot",
    icon: "🥕",
    energyBoost: 14,
    happinessBoost: 15,
    hungerReduction: 15,
    cost: 8,
    description: "Crispy vitamin-rich vegetable snack for a shiny coat and bright eyes.",
  },
  {
    id: "chicken_drum",
    name: "Roast Chicken Feast",
    icon: "🍗",
    energyBoost: 50,
    happinessBoost: 45,
    hungerReduction: 60,
    cost: 65,
    description: "The ultimate hearty canine feast that completely energizes your pup!",
  },
];
